db_path: /home/nzaccagnino/go-notes/jotaku.db
editor_mode: ""
theme: dark
auto_save_interval: 0s
salt: gDgQX6uptwN7bT8iMu8J3A==
language: it
server:
    url: "http://localhost:8080"
    enabled: true
    token: ""
    username: ""
    last_sync: 0
